### PR TITLE
aex-2 rewrite

### PR DESCRIPTION
**Pull request by shekhar-shubhendu**

### CODE REVIEW

**Comment by shekhar-shubhendu** [comment]
@knarz I do not have access to resolve the conflicts here. can you fix this for me?

**Comment by knarz** [comment]
It would help if you could just bring your repo up to speed with this one

**Comment by shekhar-shubhendu** [comment]
@knarz done. looks good now I think.

**Comment by knarz** [comment]
Could you maybe see if you can clean up the apeunit branch a bit for future pull requests? thank you

**Pull request merged**
