### PR TITLE
AEX-2: Make headers more clear

### PR DESCRIPTION
**Pull request by davidyuk**
I think is much more clear to split available methods by sides that implement it instead of sides that can call them.

### CODE REVIEW

**Review by shekhar-shubhendu — COMMENTED** [review]
this makes things more confusing and should not be done.

**Comment by davidyuk** [comment]
What if in future standards we would have three or more sides, how would you explain methods that they implement? In that case, the most reasonable is to explain methods that implement every side in the definition of that side, don't you agree? We should make this change at least to be consistent with it.

**Comment by shekhar-shubhendu** [comment]
this is out of scope.

**Comment by davidyuk** [comment]
My proposal makes wallet definition less dependent on aepp definition.

**Comment by shekhar-shubhendu** [comment]
not from my perspective. it hinders the readability and confuses the reader.

**Comment by shekhar-shubhendu** [comment]
Will not be added to the document.
@knarz please close this.

**Comment by davidyuk** [comment]
@knarz if I would open an issue on the same topic would you close it as well? Shouldn't we check the opinion of the community for this before rejecting it?

**Comment by knarz** [comment]
You can open whatever issue you want. I just don't think this is a productive discussion. I don't have an opinion on the headers. The editor has the last say in this matter, seeing as this is just a cosmetic change

**Comment by knarz** [comment]
And please use the discussion link provided in the AEX in the future. That's what they are for.

**Pull request closed without merging**
