### PR TITLE
WIP: AEX-8: message signing

### PR DESCRIPTION
**Pull request by AndreasGassmann**

### CODE REVIEW

**Review by davidyuk — COMMENTED** [review]
As I know, SDK already implements something similar: https://github.com/aeternity/aepp-sdk-js/blob/1fc57af9608ceb4cacb1bc93f674f4bc14370db3/es/utils/crypto.js#L390-L403 Would be good to compare these implementations.

I think if it is necessary for an application, it can make ttl a part of the message, as we were doing for an old version of Voting app.

Maybe instead of putting code examples, it is enough to just mention the algorithm that will be used for signing?

**Comment by AndreasGassmann** [comment]
Thanks for the link, I wasn't aware that the SDK already has that functionality. It looks like the implementations are very similar, only the encoding is different.

Regarding the algorithm, we can remove the code samples if they don't belong in an AEX, but I think it's nice to see the very short code alongside the explanations for further clarification.

**Comment by shekhar-shubhendu** [comment]
@AndreasGassmann I think this can be closed.

**Comment by AndreasGassmann** [comment]
Why should this be closed?

As far as I've heard, other people have implemented message signing into their libraries / apps already. It's important we have a clear standard for this. If those people could give feedback to this proposal that would be great so we don't have multiple different implementations in our ecosystem.

**Comment by shekhar-shubhendu** [comment]
okay. Since the PR is open for some time now I thought it was not getting developed any further.
also, I was planning to add a `sign message` method in aex-2.
Would be nice if this can be merged before and I can just reference it in aex-2

**Comment by AndreasGassmann** [comment]
Do you know who the people are that should give feedback for this?

**Comment by shekhar-shubhendu** [comment]
They will be @nduchak @thepiwo @mpowaga @randomshinichi @mradkov @emil-apeunit @davidyuk

**Pull request merged**
